"""add price to products

Revision ID: b86684bd0cab
Revises: 38b1a155ee1d
Create Date: 2026-08-02 18:53:51.899025

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b86684bd0cab"
down_revision: Union[str, Sequence[str], None] = "38b1a155ee1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "price")
    # ### end Alembic commands ###
