name: CI

on: 
    push:
    pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: test
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        SECRET_KEY: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add uv
        uses: astral-sh/setup-uv@v5

      - name: Dependencies
        run: uv sync

      - name: Tests
        run: uv run pytest
